"""Plan contract helper modules for the skill-local CLI."""

from __future__ import annotations

from .artifacts import (
    parse_artifact_manifest,
    resolve_plan_artifact_path,
    validation_has_commands,
)
from .docs import adr_dir, ledger_path, plan_reference_present, resolve_repo_path
from .git import (
    git_changed_paths,
    git_current_branch,
    git_diff_paths,
    git_path_is_ignored,
    git_path_is_tracked,
)
from .markdown import (
    checklist_has_meaningful_items,
    extract_paths_from_bullets,
    file_has_meaningful_content,
    find_section,
    is_placeholder_value,
    keyed_bullets,
    normalize_value,
    parse_sections,
    section_bullets,
    section_has_meaningful_bullets,
    strip_checklist_prefix,
    strip_frontmatter,
)
from .models import (
    ArtifactEntry,
    MarkdownSection,
    PlanContext,
    PlanContractError,
    PlanMeta,
)
from .plans import (
    changed_plan_contexts,
    changed_plan_dir_names,
    current_plan_context,
    in_progress_plan_contexts,
    list_plan_contexts,
    missing_required_plan_files,
    parse_meta_yaml,
    plan_context_from_dir,
    selected_plan_context,
    strip_changed_plan_paths,
    strip_plan_local_changes,
    validate_meta_yaml,
)

__all__ = [
    "ArtifactEntry",
    "MarkdownSection",
    "PlanContext",
    "PlanContractError",
    "PlanMeta",
    "adr_dir",
    "changed_plan_contexts",
    "changed_plan_dir_names",
    "checklist_has_meaningful_items",
    "current_plan_context",
    "extract_paths_from_bullets",
    "file_has_meaningful_content",
    "find_section",
    "git_changed_paths",
    "git_current_branch",
    "git_diff_paths",
    "git_path_is_ignored",
    "git_path_is_tracked",
    "in_progress_plan_contexts",
    "is_placeholder_value",
    "keyed_bullets",
    "ledger_path",
    "list_plan_contexts",
    "missing_required_plan_files",
    "normalize_value",
    "parse_artifact_manifest",
    "parse_meta_yaml",
    "parse_sections",
    "plan_context_from_dir",
    "plan_reference_present",
    "resolve_plan_artifact_path",
    "resolve_repo_path",
    "section_bullets",
    "section_has_meaningful_bullets",
    "selected_plan_context",
    "strip_changed_plan_paths",
    "strip_checklist_prefix",
    "strip_frontmatter",
    "strip_plan_local_changes",
    "validate_meta_yaml",
    "validation_has_commands",
]
